import type { SectionData } from './types';

const BUILDER_NAMES: Record<number, string> = {
  0: 'B_WALLS',
  2: 'B_LAUNCHER',
  5: 'B_FLIPPER_LEFT',
  6: 'B_CIRCLE',
};

const SIDE_NAMES = [
  'SECTION_SIDE_BOTTOM',
  'SECTION_SIDE_TOP',
  'SECTION_SIDE_LEFT',
  'SECTION_SIDE_RIGHT',
];

const formatNum = (n: number) => {
  if (Number.isInteger(n)) {
    return String(n);
  }
  const s = n.toFixed(4).replace(/\.?0+$/, '');
  return s;
};

const formatCall = (call: number[], indent: string) => {
  const id = call[0];
  const name = BUILDER_NAMES[id] || String(id);
  const args = call.slice(1);
  if (id === 0 && args.length > 8) {
    const lines = [`${indent}[`, `${indent}  ${name},`];
    for (let i = 0; i < args.length; i += 4) {
      const chunk = args.slice(i, i + 4).map(formatNum).join(', ');
      const comma = i + 4 < args.length ? ',' : '';
      lines.push(`${indent}  ${chunk}${comma}`);
    }
    lines.push(`${indent}]`);
    return lines.join('\n');
  }
  return `${indent}[${[name, ...args.map(formatNum)].join(', ')}]`;
};

const roundCall = (call: number[]) => {
  const next = call.slice();
  if (next[0] === 0) {
    for (let i = 1; i < next.length; i++) {
      next[i] = Math.round(next[i]);
    }
    return next;
  }
  if (next.length > 1) {
    next[1] = Math.round(next[1]);
  }
  if (next.length > 2) {
    next[2] = Math.round(next[2]);
  }
  return next;
};

export const roundLevel = (
  sections: SectionData[],
  links: number[][]
): { sections: SectionData[]; links: number[][] } => {
  return {
    sections: sections.map(s => [
      Math.round(s[0]),
      Math.round(s[1]),
      Math.round(s[2]),
      Math.round(s[3]),
      s[4],
      s[5].map(roundCall),
    ]),
    links: links.map(l => [l[0], l[1], Math.round(l[2]), Math.round(l[3])]),
  };
};

export const generateLevelsTs = (
  sections: SectionData[],
  links: number[][]
): string => {
  const rounded = roundLevel(sections, links);
  sections = rounded.sections;
  links = rounded.links;
  const builderNames = new Set<string>();
  const sideNames = new Set<string>();
  for (const section of sections) {
    for (const call of section[5]) {
      const name = BUILDER_NAMES[call[0]];
      if (name) {
        builderNames.add(name);
      }
    }
  }
  for (const link of links) {
    const name = SIDE_NAMES[link[1]];
    if (name) {
      sideNames.add(name);
    }
  }

  const imports = [...builderNames, ...sideNames].sort();
  const importBlock =
    imports.length > 0
      ? `import {\n  ${imports.join(',\n  ')},\n} from './builders';\n`
      : `import {} from './builders';\n`;

  const sectionLines: string[] = [];
  for (const s of sections) {
    const calls = s[5];
    if (calls.length === 0) {
      sectionLines.push(
        `  [${formatNum(s[0])}, ${formatNum(s[1])}, ${formatNum(s[2])}, ${formatNum(s[3])}, ${s[4]}, []],`
      );
      continue;
    }
    const callStr = calls.map(c => formatCall(c, '      ')).join(',\n');
    sectionLines.push(
      `  [
    ${formatNum(s[0])},
    ${formatNum(s[1])},
    ${formatNum(s[2])},
    ${formatNum(s[3])},
    ${s[4]},
    [
${callStr},
    ],
  ],`
    );
  }

  const linkLines = links.map(l => {
    const side = SIDE_NAMES[l[1]] || String(l[1]);
    return `  [${l[0]}, ${side}, ${formatNum(l[2])}, ${formatNum(l[3])}],`;
  });

  return `${importBlock}
export type SectionData = [
  number,
  number,
  number,
  number,
  number,
  number[][],
];

/**
 * x, y, w, h, bg, builder calls.
 * Generated by the editor.
 */
export const SECTIONS: SectionData[] = [
${sectionLines.join('\n')}
];

/** section, side, localOffset, width */
export const LINKS: number[][] = [
${linkLines.join('\n')}
];
`;
};
