import {
  B_CIRCLE,
  B_FLIPPER_LEFT,
  B_LAUNCHER,
  B_WALLS,
  SECTION_SIDE_BOTTOM,
  SECTION_SIDE_LEFT,
  SECTION_SIDE_RIGHT,
  SECTION_SIDE_TOP,
} from './builders';

export type SectionData = [
  number,
  number,
  number,
  number,
  number,
  number[][],
];

/**
 * x, y, w, h, bg, builder calls.
 * Generated by the editor.
 */
export const SECTIONS: SectionData[] = [
  [
    0,
    0,
    400,
    520,
    0,
    [
      [
        B_WALLS,
        2, 301, 115, 358,
        371, 297, 250, 358,
        0, 413, 373, 473,
        350, 200, 400, 280,
        350, 200, 400, 108,
        373, 474, 373, 520,
        372, 445, 372, 300,
        0, 86, 96, 0,
        0, 160, 160, 198,
        299, 156, 400, 107
      ],
      [B_FLIPPER_LEFT, 114, 369, 0.45, -0.55, 0],
      [B_FLIPPER_LEFT, 304, 165, 0.45, -0.55, 1],
      [B_LAUNCHER, 387, 489, 0, -1, 950, 36],
      [B_CIRCLE, 142, 104, 10, 1.2, 40, 0, 0, 1.2],
      [B_CIRCLE, 82, 256, 10, 1.2, 40, 0, 0, 1.2],
    ],
  ],
  [
    0,
    -400,
    400,
    400,
    1,
    [
      [
        B_WALLS,
        0, 146, 163, 0,
        66, 342, 0, 318,
        20, 302, 75, 208,
        217, 69, 358, 48,
        297, 199, 338, 214,
        297, 400, 400, 306,
        52, 372, 102, 400,
        42, 339, 52, 371,
        254, 111, 400, 102,
        145, 400, 135, 369
      ],
      [B_FLIPPER_LEFT, 67, 350, 0.45, -0.55, 0],
      [B_CIRCLE, 230, 263, 3, 1, 40, 12, 0, 0],
      [B_LAUNCHER, 153, 370, 0, -1, 1250, 36],
    ],
  ],
  [400, -400, 640, 400, 2, []],
];

/** section, side, localOffset, width */
export const LINKS: number[][] = [
  [0, SECTION_SIDE_TOP, 179, 100],
  [1, SECTION_SIDE_BOTTOM, 179, 100],
  [1, SECTION_SIDE_RIGHT, 150, 100],
  [2, SECTION_SIDE_LEFT, 150, 100],
];
