import {
  B_CIRCLE,
  B_FLIPPER_LEFT,
  B_LAUNCHER,
  B_WALLS,
  SECTION_SIDE_BOTTOM,
  SECTION_SIDE_LEFT,
  SECTION_SIDE_RIGHT,
  SECTION_SIDE_TOP,
} from './builders';

export type SectionData = [
  number,
  number,
  number,
  number,
  number,
  number[][],
];

/**
 * x, y, w, h, bg, builder calls.
 * Generated by the editor.
 */
export const SECTIONS: SectionData[] = [
  [
    0,
    0,
    400,
    600,
    0,
    [
      [
        B_WALLS,
        0, 419, 122, 463,
        369, 420, 275, 462,
        372, 573, 372, 600,
        0, 500, 373, 560,
        372, 596, 400, 596,
        350, 200, 400, 280,
        350, 200, 400, 108,
        369, 301, 369, 534
      ],
      [B_FLIPPER_LEFT, 123, 471, 0, 0],
      [B_FLIPPER_LEFT, 275, 470, 0, 0, 1],
      [B_LAUNCHER, 384, 582],
      [B_CIRCLE, 95, 179, 10, 1.2, 40, 22, 0, 1.2],
      [B_CIRCLE, 288, 92, 10, 1.2, 40, 22, 0, 1.2],
    ],
  ],
  [
    0,
    -400,
    400,
    400,
    1,
    [
      [
        B_WALLS,
        0, 146, 163, 0,
        66, 342, 0, 318,
        20, 302, 75, 208,
        217, 69, 358, 48,
        297, 199, 338, 214,
        297, 400, 400, 306,
        52, 372, 102, 400,
        42, 339, 52, 371,
        254, 111, 400, 102,
        145, 400, 135, 369
      ],
      [B_FLIPPER_LEFT, 67, 350, 0, -0.55],
      [B_CIRCLE, 230, 263, 3, 1, 40, 12, 0, 0],
      [B_LAUNCHER, 153, 370],
    ],
  ],
  [400, -400, 640, 400, 2, []],
];

/** section, side, localOffset, width */
export const LINKS: number[][] = [
  [0, SECTION_SIDE_TOP, 179, 100],
  [1, SECTION_SIDE_BOTTOM, 179, 100],
  [1, SECTION_SIDE_RIGHT, 150, 100],
  [2, SECTION_SIDE_LEFT, 150, 100],
];
